# Generated by Django 4.1.1 on 2022-10-08 17:00

from django.db import migrations, models
import django.db.models.deletion
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', s3direct.fields.S3DirectField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_images', to='portal.product')),
            ],
            options={
                'verbose_name_plural': 'Images',
            },
        ),
    ]
